### ISSUE TITLE
[Bug]: Cannot get tmux pane ID

### ISSUE THREAD

**Issue by nikolasetiawan** [mrjones2014/smart-splits.nvim#121]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

0.9.1

### Multiplexer Integration

tmux

### Multiplexer Version

3.2a

### Steps to Reproduce

try to move pane

### Expected Behavior

move

### Actual Behavior

no

### Minimal Configuration to Reproduce

-

### Additional Details and/or Screenshots

I found that I'm unable to change the pane with an error `Failed to get multiplexer pane ID`.

After some investigation, the root cause is probably unrelated to the plugin. But I will raise this question anyway in case you have a similar experience with it. Feel free to close this issue if you think it's too unrelated to the plugin.

For some reason, I can't get tmux to print anything from inside neovim. The easiest way for me to check is just by running the command `:! tmux -V` which should print the version of tmux. But it shows an empty string instead.

My guess is there's some permission error or something, but nvim doesn't print it.

I installed both my nvim and tmux from snap package.

Let me know what you think, or feel free to close the issue.

**Comment by mrjones2014** [comment]
It’s most likely due to snap package sandboxing.

if you have a minimal configuration I can see if I can reproduce in non-snap package environment.

**Comment by nikolasetiawan** [comment]
I just spun up a new ubuntu VM and it's working fine there. So probably some permission error on my side. I'll investigate further on this. Thank you for your reply though,
