### ISSUE TITLE
listen to key repeats after leader

### ISSUE THREAD

**Issue by bradyslot** [mrjones2014/smart-splits.nvim#13]
In the way I use tmux, I press the prefix key then use the arrow keys for any direction and it will listen for repeated key presses for resizing panes.
I believe there's a 500ms timeout by default.
The resize behavior is identical to what this plugin hopes to achieve, so it's logically consistent with what I'm used to.
I would just love the ability to press the leader key and have it listen for a resize command for 500ms and repeat.
Currently I have this plugin mapped to ctrl+arrowkeys, which also works great, and am happy to settle for if this feature turns out to nonsensical.

example tmux.conf
```tmux
# resizing with arrow keys because they're hardly used
unbind Left
bind -r Left resize-pane -L 5
unbind Right
bind -r Right resize-pane -R 5
unbind Down
bind -r Down resize-pane -D 5
unbind Up
bind -r Up resize-pane -U 5
```

**Comment by mrjones2014** [comment]
I'm interested in experimenting with this but currently I have no idea how that would be implemented. I might get some time this weekend.

**Comment by bradyslot** [comment]
Perhaps the secrets lie within submodules?
https://vi.stackexchange.com/questions/3632/how-to-repeat-a-mapping-when-keeping-key-pressed

**Comment by mrjones2014** [comment]
Ooh, great resource. Will definitely do some tinkering with that this weekend.
