### ISSUE TITLE
[Feature]: Add commands for buffer swap

### ISSUE THREAD

**Issue by rmarquis** [mrjones2014/smart-splits.nvim#137]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

In #45, support for swapping buffers directionally was added. However, related commands (similarly as `SmartResizeLeft` or `SmartCursorMoveLeft`) were not added.

Is there any reason for this, or has this simply be forgotten?

If the reason is the latter, adding commands to control buffer, (such as `SmartBufferMoveLeft`, `SmartBufferMoveDown`, `SmartBufferMoveUp`, `SmartBufferMoveRight`) would be appreaciated. It would ease keymapping, and also add consistency to the available commands.

**Comment by mrjones2014** [comment]
No reason they weren’t added, I think I just forgot.

would gladly take a PR or I can get to it next week.
