### ISSUE TITLE
ignored_filetypes and ignored_buftypes not working

### ISSUE THREAD

**Issue by mehalter** [mrjones2014/smart-splits.nvim#14]
I can't seem to get the ignored_filetypes or ignored_buftypes options working No matter what I set it doesn't change the edge detection to ignore the set filetypes. This includes when I don't modify the setup and the default does `nofile`/`quickfix`/`prompt`. If I have the quickfix open and resize a window that isn't the quickfix it will resize it instead of keeping it as a constant size.

**Comment by mrjones2014** [comment]
Whoops. I think I accidentally removed that behavior while debugging the other issue you had opened the other day. This should be fixed now by 96ae8e81654d4e92023e16b2b7b950fd15376fc4

**Comment by mrjones2014** [comment]
Note that I also updated the config table and how you set it: https://github.com/mrjones2014/smart-splits.nvim#configuration

**Comment by mehalter** [comment]
Hm, maybe I'm doing something wrong or misinterpretting how it should work  but I don't think that commit fixed it

**Comment by mehalter** [comment]
oh  wait I see, I think that the buftypes is working but not the filetypes

**Comment by mrjones2014** [comment]
Try again with 6dbd63baa7fddde6d83dc32851fa113749cf0af7

**Comment by mehalter** [comment]
One thing that I think is slightly unexpected is if there is only 2 windows say a quickfix list at the bottom and my normal file buffer. if I have `quickfix` as an ignored filetype and I try to resize my normal buffer up/down it resizes the quickfix where I would expect if I have it in the `ignored_filetypes` then I would _need_ to go to the quickfix window to resize it.

**Comment by mehalter** [comment]
In this case would it make sense for no resizing to happen just as if I had only ones single window open

**Comment by mrjones2014** [comment]
hmm... I'm not sure how it should behave in that case. If a buffer and quickfix are the only 2 windows, and you try to resize vertically, wouldn't you expect it to resize, despite ignore file/buf types?

Otherwise what would be the point of pressing the resize keymap to begin with?
