### ISSUE TITLE
Does smart-splits.nvim support to quit the resize mode by pressing 'q'

### ISSUE THREAD

**Issue by fgheng** [mrjones2014/smart-splits.nvim#18]
Hello, I want to quit the resize mode using 'q', how to set it.

**Comment by fgheng** [comment]
and how to close the notifications while in or out the resize mode.

**Comment by mrjones2014** [comment]
@fgheng why'd you close this? I was going to make it configurable

**Comment by fgheng** [comment]
> @fgheng why'd you close this? I was going to make it configurable

Oh, I am sorry, because I think it is reasonable to use <ESC>. But I'm also looking forward to  a configurable option of this.

**Comment by mrjones2014** [comment]
Updated. There's config options for it now.
