### ISSUE TITLE
Provide an option to disable print() in resize-mode.lua?

### ISSUE THREAD

**Issue by Frederick888** [mrjones2014/smart-splits.nvim#19]
Without any special overriding of vim.notify(), [1][2] just appear to be two duplicate lines when `cmdheight` > 1.

I wonder if it's ok to remove the print() calls? Or if this was intentional, can we have an option to suppress it? Thank you.

[1] https://github.com/mrjones2014/smart-splits.nvim/blob/884172034a55ef4ee4fdddc0a1cbb09c767ac032/lua/smart-splits/resize-mode.lua#L26-L27
[2] https://github.com/mrjones2014/smart-splits.nvim/blob/884172034a55ef4ee4fdddc0a1cbb09c767ac032/lua/smart-splits/resize-mode.lua#L43-L44

**Comment by mrjones2014** [comment]
`require('smart-splits').setup({ resize_mode_silent = true })`

**Comment by Frederick888** [comment]
@mrjones2014 That triggers an early return and then nothing gets printed to the command area. I still want the message, but just one line instead of two duplicate lines... 😅

**Comment by Frederick888** [comment]
@mrjones2014 Yes. Currently they look like this in my Neovim (`cmdheight` = 2):

![image](https://user-images.githubusercontent.com/4507647/172162374-dc018ee4-7f59-4c02-addb-3c72c0631290.png)

And if I set `cmdheight` to 1:

![image](https://user-images.githubusercontent.com/4507647/172162560-61915f63-75d1-471c-9d07-924bfd8b8d10.png)

**Comment by mrjones2014** [comment]
Ah, I think I just didn't realize because I'm using a notifications plugin for Neovim. Without one, `vim.notify` and `print` both go to the command area.

I'll remove the `print` and leave just the `vim.notify`.
