### ISSUE TITLE
[Feature]: Always move in multiplexer if current Vim window is floating

### ISSUE THREAD

**Issue by toupeira** [mrjones2014/smart-splits.nvim#201]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

The current behaviour with floating windows feels a bit weird to me: The previous Vim window is selected, and then the movement is performed from there (either moving to another Vim window, or multiplexer split).

If I have a big floating window open like FZF or Lazy, the Vim cursor moves to a window behind it, so I can't actually see the buffer and have to get back to the floating window to close it.

What I'd like to do instead is ignore Vim windows completely if the current window is floating, and always move to another multiplexer split.

Happy to submit a PR for this, maybe behind an option called `ignore_floating` which defaults to false?

**Comment by mrjones2014** [comment]
That sounds reasonable. Let's make it an option so that users can preserve the current behavior if they wish. How about something like:

```lua
float_win_behavior = 'previous'|'mux'
```

**Comment by mrjones2014** [comment]
And let's keep `'previous'` as the default value for the option.

**Comment by toupeira** [comment]
@mrjones2014 sweet, that sounds great!

I pushed a PR at https://github.com/mrjones2014/smart-splits.nvim/pull/202, thanks for taking a look :bow:

**Comment by mrjones2014** [comment]
Whoops, looks like this didn’t get auto closed for some reason. This is implemented in #202
