### ISSUE TITLE
[Bug]: Can't move out from neovim to kitty window

### ISSUE THREAD

**Issue by letieu** [mrjones2014/smart-splits.nvim#209]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Neovim Version

NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478

### Multiplexer Integration

Kitty

### Multiplexer Version

itty 0.35.1 created by Kovid Goyal

### Steps to Reproduce

1. Create Kitty vertical split at the bottom of neovim
2. Move from kitty window to neovim: Work
3. **Move from neovim to kitty window: Nothing happend**
4. Resize: Work both when focus on neovim and kitty
5. Try to revert to version v1.4.0: Move work again

### Expected Behavior

Need to move from neovim to kitty window

### Actual Behavior

Can't move from neovim to kitty, move inside neovim still work

### Minimal Configuration to Reproduce

```lua
-- Config with lazy nvim
  {
    'mrjones2014/smart-splits.nvim',
    build = './kitty/install-kittens.bash',
    config = function()
      require('smart-splits').setup({})

      vim.keymap.set('n', '<A-h>', require('smart-splits').resize_left)
      vim.keymap.set('n', '<A-j>', require('smart-splits').resize_down)
      vim.keymap.set('n', '<A-k>', require('smart-splits').resize_up)
      vim.keymap.set('n', '<A-l>', require('smart-splits').resize_right)
      -- moving between splits
      vim.keymap.set('n', '<C-h>', require('smart-splits').move_cursor_left)
      vim.keymap.set('n', '<C-j>', require('smart-splits').move_cursor_down)
      vim.keymap.set('n', '<C-k>', require('smart-splits').move_cursor_up)
      vim.keymap.set('n', '<C-l>', require('smart-splits').move_cursor_right)
      vim.keymap.set('n', '<C-\\>', require('smart-splits').move_cursor_previous)
    end
  }

```

**Comment by mrjones2014** [comment]
Is there anything relevant in the logs? Also can you see if you can reproduce on this commit? f5df5b6dc4aa2c8d8c81e3c06dd2c3b6ff05dacf

**Comment by letieu** [comment]
> Is there anything relevant in the logs? Also can you see if you can reproduce on this commit? [f5df5b6](https://github.com/mrjones2014/smart-splits.nvim/commit/f5df5b6dc4aa2c8d8c81e3c06dd2c3b6ff05dacf)

How can I check the logs

**Comment by letieu** [comment]
> `:SmartSplitsLog<CR>`

I'll check and report you soon. I use wayland if you mind. I need sleep right now🙂‍↔️

Maybe I'll try fix and create a PR if it really a bug.

**Comment by letieu** [comment]
I don't know why but now I upgrade to newest version and I work like a charm
