### ISSUE TITLE
[Feature]: add support for hyprland

### ISSUE THREAD

**Issue by sandangel** [mrjones2014/smart-splits.nvim#242]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

It would be nice to have hyprland support for this amazing plugin. Right now I'm only found this plugin but it's not working: https://github.com/nuchs/vim-hypr-nav/blob/main/plugin/vim-hypr-nav.vim

**Comment by mrjones2014** [comment]
I would consider a PR for this with a commitment of ongoing maintenance, but since I don't use Hyprland, I wouldn't want to commit to maintaining it. Sorry.
