### ISSUE TITLE
Request: Mappings

### ISSUE THREAD

**Issue by Aonodensetsu** [mrjones2014/smart-splits.nvim#26]
Allow remapping the hjkl keys  in resize mode (for example - I want to use the arrow keys instead, I don't find hjkl intuitive and have remapped them to arrows everywhere else). If such a feature is available, please document it.

**Comment by mrjones2014** [comment]
Sure thing. Done in [4e703fa](https://github.com/mrjones2014/smart-splits.nvim/commit/4e703faef1201f7d4159a01a80ae1adabff6b185)

**Comment by mrjones2014** [comment]
whoops, it's bugged. reverting for now

**Comment by mrjones2014** [comment]
done in [5c4f791](https://github.com/mrjones2014/smart-splits.nvim/commit/5c4f791e0b9cc8294dd965532d97dec05ef9a8cc)

**Comment by Aonodensetsu** [comment]
Thanks but it does not work, the keys are still hjkl regardless of the remap.
![image](https://user-images.githubusercontent.com/58662350/183292533-2065ba8e-70db-4315-a914-03880515b86d.png)
