### ISSUE TITLE
Reopen #26 (custom mappings)

### ISSUE THREAD

**Issue by Aonodensetsu** [mrjones2014/smart-splits.nvim#27]
Thanks for adding the feature, but unfortunately it does not work for me, I assume it does not like meta keys like the *\<arrows\>*.
![image](https://user-images.githubusercontent.com/58662350/183292940-40d99b37-df50-4505-925d-0491cf47bbe6.png)

**Comment by Aonodensetsu** [comment]
FYI [this link](https://dot.bluecom.dev/configs/get/nvim) contains the always-newest version of my nvim config.

**Comment by mrjones2014** [comment]
Fixed by [c8d80d9](https://github.com/mrjones2014/smart-splits.nvim/commit/c8d80d90f3c783ac0ea21f256c74d541a7b66a72)
