### ISSUE TITLE
[Feature]: Support for ghostty terminal splits

### ISSUE THREAD

**Issue by ricardoraposo** [mrjones2014/smart-splits.nvim#273]
### Similar Issues

- [X] Before filing, I have searched for similar issues.

### Description

Would be nice to get the same behavior of split swapping for ghostty terminal splits

**Comment by mrjones2014** [comment]
As far as I can tell, it isn't possible. Ghostty offers no API or CLI interface to the multiplexer.

I also don't plan to use Ghostty, but if it does become possible, I'd take a PR if someone from the community wanted to implement it.

**Comment by mrjones2014** [comment]
Still not possible it seems.
