### ISSUE TITLE
[FEATURE]: disabling circular/warp when hitting edge

### ISSUE THREAD

**Issue by nikolasetiawan** [mrjones2014/smart-splits.nvim#38]
Is there any way to stop when hitting an edge instead of cycling / warping?

**Comment by mrjones2014** [comment]
Not at the moment, I can add a config setting later this week.

**Comment by mrjones2014** [comment]
Fixed in #39

**Comment by nikolasetiawan** [comment]
Hi, @mrjones2014 the edge wrapping option works, but now it won't jump to a tmux split pane. Is this a bug, or do other options need to be set?

**Comment by mrjones2014** [comment]
isa bug

**Comment by mrjones2014** [comment]
Fixed.
