### ISSUE TITLE
How to not break tmux zoom mode?

### ISSUE THREAD

**Issue by towry** [mrjones2014/smart-splits.nvim#40]
I use `<F12>` to toggle the zoom mode, in tmux zoom mode,
if I switch panel in vim, it will un zoom the tmux which is annoying.

**Expected behavior**
Ability to detect tmux zoom mode.

**Comment by mrjones2014** [comment]
I’m not familiar with tmux zoom mode but I can look into it 👍

**Comment by mrjones2014** [comment]
@towry to clarify, what is the desired behavior here? Just don't do anything when the current pane is zoomed?

**Comment by towry** [comment]
@mrjones2014 Like https://github.com/christoomey/vim-tmux-navigator#tmux did, `let g:tmux_navigator_disable_when_zoomed = 1`

**Comment by mrjones2014** [comment]
@towry can you test this PR and make sure it works as intended? if so I will merge: https://github.com/mrjones2014/smart-splits.nvim/pull/41

**Comment by towry** [comment]
@mrjones2014 You are amazing! ❤️ It works!
