### ISSUE TITLE
[FEATURE]: Swap windows directionally

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/smart-splits.nvim#44]
**Is your feature request related to a problem? Please describe.**

Run `:vsp` then you want to swap the buffers directionally

**Describe the solution you'd like**

A function to swap the buffer with the buffer from the window next to it

**Describe alternatives you've considered**
Other plugins

**Additional context**

**Comment by CKolkey** [comment]
Just a heads up, the cursor doesn't follow the buffer as you move it. Bit confusing.

**Comment by mrjones2014** [comment]
This is how I intended the feature to work. I’m open to changing it with an option if you open a new issue.
