### ISSUE TITLE
[FEATURE]: Directional moving of windows

### ISSUE THREAD

**Issue by jemag** [mrjones2014/smart-splits.nvim#46]
**Is your feature request related to a problem? Please describe.**
I would like to move windows directionally. 
Currently swapping will keep the cursor on the current window instead of moving with the swapped buffer which is a bit unintuitive and prevents you from moving you window several positions in  a row.

For example, moving the window on the left to the center :
![image](https://user-images.githubusercontent.com/7985687/221932619-36503cbf-2f5b-4ee0-a677-5ca1559b76bb.png)
This would not be possible with the current implementation of swapping (at least without moving after each swap)

**Describe the solution you'd like**
Either make a new method that allows directional moving of a window or allow cursor to follow current buffer while swapping.

**Describe alternatives you've considered**
Cry while doing a series of swap and move combinations instead of a single action.

**Comment by mrjones2014** [comment]
>Cry while doing a series of swap and move combinations instead of a single action.

😂 

So, to clarify, basically what you're asking for is for the cursor to follow the buffer when you swap a buffer to an adjacent window?

If so, this is do-able. 

> Either make a new method that allows directional moving of a window or allow cursor to follow current buffer while swapping.

Which of these would be better in your opinion:

- a config option for the cursor to follow the moved buffer
- a separate set of methods, so that you can use both behaviors

**Comment by jemag** [comment]
I do think being able to use both behaviors would be slightly more optimal, although I would probably use the directional moving/cursor following method most of the time. I also doubt that general users would complain about having more choices

**Comment by mrjones2014** [comment]
Okay, with that said then what I'll probably do is add a config option to set the _default_ behavior, and also make the `swap_buffer_[direction]` methods take an `opts` table so you may call it like `require('smart-splits').swap_buffer_left({ move_cursor = true })`
