### ISSUE TITLE
bug: SmartResizeLeft/Right echos message into command line

### ISSUE THREAD

**Issue by cwqt** [mrjones2014/smart-splits.nvim#6]
Calling `:SmartResizeLeft` or `Right` puts a message into the command line that means I have to press Enter on every resize, this doesn't happen for Up or Down though

<img width="434" alt="image" src="https://user-images.githubusercontent.com/61694629/159585303-42b92c02-1162-4781-8f7d-70129a84df15.png">

I've silencing this via:

```vim
map <silent><A-H> :SmartResizeLeft 4<CR>
map <silent><A-J> :SmartResizeDown 2<CR>
map <silent><A-K> :SmartResizeUp 2<CR>
map <silent><A-L> :SmartResizeRight 4<CR>
```

but no avail

**Comment by mrjones2014** [comment]
whoooops I left some print statements in there, my bad 😅

**Comment by mrjones2014** [comment]
sorry about that 😓

**Comment by cwqt** [comment]
no worries! thanks for the quick fix :)
