### ISSUE TITLE
[FEATURE]:  kitty directional resize

### ISSUE THREAD

**Issue by tobealive** [mrjones2014/smart-splits.nvim#66]
Great to see how the plugin has evolved! Thank you for your art!

Based on the idea of triggering kitty's `resize_window <wider/narrower/taller/shorter>` command depending on window layout and position, I did some research into the possibility of directional resizing with kitty.

The most promising find was based on this issue: 
https://github.com/kovidgoyal/kitty/issues/4684
It appeared that the issue opener had solved the request, so I took the liberty of looking into his dotfiles, where I found this little gem of a kitten: 
https://github.com/chancez/dotfiles/blob/master/kitty/.config/kitty/relative_resize.py

His dots are under MIT license and I thought this could serve for extending smart-resize's kitty implementation. If it's not too much trouble, perhaps adding directional resize support could be feasible. What are your thoughts on that?

**Comment by mrjones2014** [comment]
Nice find, I think I can make it work with that kitten

**Comment by mrjones2014** [comment]
Resolved by #67
