### ISSUE TITLE
E5113: Error while calling lua chunk...attempt to call field 'nvim_add_user_command' (a nil value)

### ISSUE THREAD

**Issue by AGou-ops** [mrjones2014/smart-splits.nvim#7]
I get this error when I open a file:

```bash
处理 /Users/agou-ops/.vim/plugged/smart-splits.nvim/plugin/smart-splits.lua 时发生错误:
E5113: Error while calling lua chunk: ...s/.vim/plugged/smart-splits.nvim/plugin/smart-splits.lua:13: attempt to call field 'nvim_add_user_command' (a nil value)
stack traceback:
        ...s/.vim/plugged/smart-splits.nvim/plugin/smart-splits.lua:13: in main chunk
```

- nvim version: 0.6.1
- MacOS 12.3
- package manager: vim-plug
- latest plugin

And my config is default:
![image](https://user-images.githubusercontent.com/57939102/159636781-946df4b9-3b03-4ff0-b968-7383fad18748.png)

**Comment by mrjones2014** [comment]
Ah, that function might only be available in nightly releases for now. I can make an update to define commands the old way.

**Comment by AGou-ops** [comment]
Thanks. I'm waiting for you.

**Comment by mrjones2014** [comment]
@AGou-ops should be fixed now.

**Comment by AGou-ops** [comment]
Yes, it works. Thank you very much!
