### ISSUE TITLE
[Meta]: Wezterm mux support notice

### ISSUE THREAD

**Issue by phgz** [mrjones2014/smart-splits.nvim#99]
### Category

Docs

### Description

Hi,

Really great plugin which I was excited to try. However, for the integration with Wezterm, it only works if you are not multiplexing/ssh, as in

```lua
local function is_vim(pane)
  local process_name = basename(pane:get_foreground_process_name())
  return process_name == 'nvim' or process_name == 'vim'
end
```

The `pane:get_foreground_process_name()` has limitations (https://wezfurlong.org/wezterm/config/lua/pane/get_foreground_process_name.html?h=get_foreground_process_name):

> This information is only available for local panes. Multiplexer panes do not report this information. Similarly, if you are using eg: ssh to connect to a remote host, you won't be able to access the name of the remote process that is running.

This bit of information could be added in the docs for Wezterm.

Thanks!

**Comment by mrjones2014** [comment]
Hmm, wouldn't this apply to all mux backends? I don't think any would report the foreground process name over an SSH boundary, or am I mistaken?

**Comment by phgz** [comment]
I don't know about kitty, but TMUX over SSH still does report foreground process.

**Comment by phgz** [comment]
I tried kitty, and it does not seem to work over SSH either. So only TMUX supports this feature.

**Comment by mrjones2014** [comment]
Alright, thanks for testing that. I'll update the docs.

**Comment by mrjones2014** [comment]
Opened #101 for this but it would be great if there was any way around this limitation.
